apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-app-pvc
  namespace: k8cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
